// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LA5-nuqzSpwXWYRpYA2Dkts404R569Y',
    appId: '1:646002758359:web:8887b7d60de3bd7398d692',
    messagingSenderId: '646002758359',
    projectId: 'ai-planner-29261',
    authDomain: 'ai-planner-29261.firebaseapp.com',
    storageBucket: 'ai-planner-29261.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qtnq_VF5zJ1W4zaI_kEX0xW0hrrlTec',
    appId: '1:646002758359:android:a3d4e77beba5d07998d692',
    messagingSenderId: '646002758359',
    projectId: 'ai-planner-29261',
    storageBucket: 'ai-planner-29261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVSqKwslviXS0lKFlcnI53SqRZGZ7r8q0',
    appId: '1:646002758359:ios:467318e35c8686ee98d692',
    messagingSenderId: '646002758359',
    projectId: 'ai-planner-29261',
    storageBucket: 'ai-planner-29261.firebasestorage.app',
    iosBundleId: 'com.example.aiPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVSqKwslviXS0lKFlcnI53SqRZGZ7r8q0',
    appId: '1:646002758359:ios:467318e35c8686ee98d692',
    messagingSenderId: '646002758359',
    projectId: 'ai-planner-29261',
    storageBucket: 'ai-planner-29261.firebasestorage.app',
    iosBundleId: 'com.example.aiPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3LA5-nuqzSpwXWYRpYA2Dkts404R569Y',
    appId: '1:646002758359:web:dc8a9f6dd85f4a5398d692',
    messagingSenderId: '646002758359',
    projectId: 'ai-planner-29261',
    authDomain: 'ai-planner-29261.firebaseapp.com',
    storageBucket: 'ai-planner-29261.firebasestorage.app',
  );
}
